### ISSUE TITLE
can I use endpoint instead of base_url?

### ISSUE THREAD

**Issue by guo-tt** [CosmosShadow/gptpdf#12]
for internal usage, we have internal azure openai endpoint instead of base_url and got this error

`openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}
ERROR:root:LLM(Large Languate Model) error, Please check your key or base_url, or network`

**Comment by CosmosShadow** [comment]
see https://github.com/CosmosShadow/gptpdf/blob/main/test/test.py. for Azure endpoint
