### ISSUE TITLE
Prompt error

### ISSUE THREAD

**Issue by musitafa0032** [CosmosShadow/gptpdf#19]
I used custom prompts, but it shows error as pic (I removed the keys and file path dir)
<img width="760" alt="image" src="https://github.com/CosmosShadow/gptpdf/assets/55053337/cc08c3ae-099f-400c-9efb-830e9ac96770">

I checked the source code, should we add code to

```
if isinstance(prompt, dict) and 'prompt' in prompt:
        prompt = prompt['prompt']
        logging.info("prompt is provided, using user prompt.")
    else:
        prompt = DEFAULT_PROMPT
        logging.info("prompt is not provided, using default prompt.")
```

**Comment by CosmosShadow** [comment]
Can you request a PR ？

**Comment by musitafa0032** [comment]
> Can you request a PR ？

Yes! I just submitted PR. Could you please help review it? Thank you!
