### ISSUE TITLE
表格内容没有正确解析

### ISSUE THREAD

**Issue by Moonlit7** [CosmosShadow/gptpdf#21]
原始文档：
<img width="500" alt="image" src="https://github.com/CosmosShadow/gptpdf/assets/2390305/ccce8f0b-1179-4787-b77a-fdfce45981a3">
解析后的markdown数据：
<img width="739" alt="image" src="https://github.com/CosmosShadow/gptpdf/assets/2390305/bffffdeb-5544-44b1-8335-284c30d631b8">
没有把表格数据提取出来，直接输出了原始图片

**Comment by zRzRzRzRzRzRzR** [comment]
现在的实现逻辑就是直接输出了原始图片，可以在提示词看到

**Comment by Moonlit7** [comment]
直接输出原始图片，那解析后的mardown数据在哪里？

**Comment by CosmosShadow** [comment]
> 直接输出原始图片，那解析后的mardown数据在哪里？

原始数据没有了。
