### ISSUE TITLE
not work with `qwen-vl-max` as provide unsupported param: `temperature`

### ISSUE THREAD

**Issue by youzipi** [CosmosShadow/gptpdf#24]
not work with `qwen-vl-max` as provide not supported param: `temperature`

code:
```py
from GeneralAgent import Agent

models = [

    ('qwen-vl-max', 6000, 'sk-0xxx', 'https://dashscope.aliyuncs.com/compatible-mode/v1'),
]

for model, token_limit, api_key, base_url in models:
    agent = Agent('You are a helpful agent.', model=model, token_limit=token_limit, api_key=api_key, base_url=base_url)
    agent.user_input('介绍一下成都')
```

error:
```py
openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_parameter', 'param': None, 'message': "'temperature' is not support for vl model now", 'type': 'invalid_request_error'}}
```

error location:
```py
GeneralAgent.skills.llm_inference.llm_inference
```
<img width="1038" alt="image" src="https://github.com/CosmosShadow/gptpdf/assets/5629307/574f9409-fdcc-4bda-bda9-ed532742203e">

**Comment by zRzRzRzRzRzRzR** [comment]
已经修复，https://github.com/CosmosShadow/GeneralAgent/pull/11 PR中

**Comment by CosmosShadow** [comment]
Update to gptpdf==0.0.13

**Comment by eruca** [comment]
版本已升级至0.0.13，使用parse_pdf，还是这个错误：
```bash
2024-07-12 12:06:53,818 - INFO - HTTP Request: POST https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions "HTTP/1.1 400 Bad Request"
2024-07-12 12:06:53,822 - ERROR - Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': 'Range of max_tokens should be [1, 1500]', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-d479aeb6-489a-9d6f-8ed9-164a106146e8'}
```

**Comment by CosmosShadow** [comment]
> 版本已升级至0.0.13，使用parse_pdf，还是这个错误：
> 
> ```shell
> 2024-07-12 12:06:53,818 - INFO - HTTP Request: POST https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions "HTTP/1.1 400 Bad Request"
> 2024-07-12 12:06:53,822 - ERROR - Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': 'Range of max_tokens should be [1, 1500]', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-d479aeb6-489a-9d6f-8ed9-164a106146e8'}
> ```

这个报错显示你的max_token超量了。
