### ISSUE TITLE
Please set OPENAI_API_KEY in environment

### ISSUE THREAD

**Issue by zhangsh1416** [CosmosShadow/gptpdf#3]
你好，感谢你的分享，我尝试本地运行，设置了环境变量OPENAI_API_KEY和base，为什么还是运行不成功呢？
Hello, thanks for your sharing, I tried to run it locally, wrote the env variants OPENAI_API_KEY and BASE, but it still run unsuccessfully, what's the potential problem?

**Comment by yuercl** [comment]
is OPENAI_API_KEY and OPENAI_API_BASE. not `BASE`

**Comment by megadotnet** [comment]
Since OpenAI blocked request invoke from China,how to use it?

**Comment by zhangsh1416** [comment]
> Since OpenAI blocked request invoke from China,how to use it?

I'm using it from Germany,so it won't be a problem

**Comment by zhangsh1416** [comment]
> is OPENAI_API_KEY and OPENAI_API_BASE. not `BASE`
> 
> 

Thanks for replying, but I did have used OPENAI_API_BASE not BASE, there could be some other problems.

**Comment by CosmosShadow** [comment]
See test/.env.example OPENAI_API_BASE.
