### ISSUE TITLE
Azure OpenAI setting problem

### ISSUE THREAD

**Issue by irene0881217** [CosmosShadow/gptpdf#32]
Hi I encountered an error when using Azure OpenAI.
I already set the api_key, base_url and model that I used in another project.
However this error occured :
Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
ERROR - LLM(Large Languate Model) error, Please check your key or base_url, or network

I was wondering what else I should set? Thanks!

**Comment by CosmosShadow** [comment]
see readme carefully. Set model by azure_xxxx where xxxx is your deploy name, not openai model name.
