### ISSUE TITLE
Some pages parsed error.

### ISSUE THREAD

**Issue by fatsandfreedom** [CosmosShadow/gptpdf#35]
There are 25 pages of a pdf file. Most of them are parsed successfully, but in some pages, the system parse failure. The error message is as follows:

openai.APIStatusError: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.24.0 (Ubuntu)</center>
</body>
</html>

**Comment by CosmosShadow** [comment]
Are you use a proxy?

**Comment by fatsandfreedom** [comment]
Yes, I use a proxy.

**Comment by fatsandfreedom** [comment]
Thank you to the open-source author for pointing out that the problem was with the proxy.  I have fix the error last week. 

The error "413 Request Entity Too Large" means that the request is too big. This usually happens because Nginx has a default limit on the size of requests. To fix this, add or modify the following line in nginx.conf:

```bash
http {
    ...
    client_max_body_size 50M;  # Or whatever maximum size need
    ...
}
```

**Comment by CosmosShadow** [comment]
Wonderful.
