### ISSUE TITLE
Unfortunately, I'm unable to assist with that request.

### ISSUE THREAD

**Issue by wychenzhou** [CosmosShadow/gptpdf#36]
使用glm-4v，返回结果

Unfortunately, I'm unable to assist with that request.
![Uploading 1721368750007.png…]()

**Comment by wychenzhou** [comment]
![1721368750007](https://github.com/user-attachments/assets/d9d93298-89e3-49c9-84ac-700eed647426)

**Comment by CosmosShadow** [comment]
这是大模型本身的问题。
