### ISSUE TITLE
About the '413' error

### ISSUE THREAD

**Issue by fatsandfreedom** [CosmosShadow/gptpdf#38]
Thank you to the open-source author for pointing out that the problem was with the proxy. I have fix the error last week.

The error "413 Request Entity Too Large" means that the request is too big. This usually happens because Nginx has a default limit on the size of requests. To fix this, add or modify the following line in nginx.conf:

http {
    ...
    client_max_body_size 50M;  # Or whatever maximum size need
    ...
}

**Comment by CosmosShadow** [comment]
Nice.
