### ISSUE TITLE
Created a quick experience UI for gptpdf.

### ISSUE THREAD

**Issue by daodao97** [CosmosShadow/gptpdf#4]
github: [gptpdf-ui](https://github.com/daodao97/gptpdf-ui)

![](https://raw.githubusercontent.com/daodao97/gptpdf-ui/main/preview.png)

## install dependencies

```shell
pip install -r requirements.txt
```

## set openai key

file `parse_pdf.py`

## start serve

```shell
python main.py
```

**Comment by CosmosShadow** [comment]
add to readme.
