### ISSUE TITLE
修改函数

### ISSUE THREAD

**Issue by sky-fly97** [CosmosShadow/gptpdf#42]
如果修改parse.py中的函数后，如何更新之前install的gptpdf？

**Comment by zRzRzRzRzRzRzR** [comment]
这个不用install的改回去就行了吧，这个改动根是否有install 无关

**Comment by sky-fly97** [comment]
> 这个不用install的改回去就行了吧，这个改动根是否有install 无关

比如我在parse.py中新增了一个函数，from gptpdf import的时候是无法import的

**Comment by sky-fly97** [comment]
咦解决了，from gptpdf.parse import就可以了
