### ISSUE TITLE
中文的PDF解析后翻译成英文了

### ISSUE THREAD

**Issue by PangDingPing** [CosmosShadow/gptpdf#46]
这是PDF的原文：
![image](https://github.com/user-attachments/assets/f07ec564-eac3-46ba-ad37-c0cf4d834ea4)
提示词要求是中文
![image](https://github.com/user-attachments/assets/b67d2d07-620e-4863-bf1c-e81a043d99fc)

解析完了自动翻译成英文了
![image](https://github.com/user-attachments/assets/e271a2b7-46db-42df-be3c-df8ceac71abb)

**Comment by CosmosShadow** [comment]
切换下更好的大模型。
