### ISSUE TITLE
需求：能否把oss或者一个稳定的图床url结合进去

### ISSUE THREAD

**Issue by samqin123** [CosmosShadow/gptpdf#48]
需求：
pdf转化后的图片链接，最好是放在云端或者类似oss上，提供服务。这样的话，oss的folder地址可以固定，图片自动命名，能不能把这个功能加进去？

**Comment by CosmosShadow** [comment]
存放到oss建议在解析完成后，写点代码进行后处理。
将这部分工作放到gptpdf里面，有些耦合了。
