### ISSUE TITLE
uploaded an unsupported image

### ISSUE THREAD

**Issue by xsser** [CosmosShadow/gptpdf#6]
openai.BadRequestError: Error code: 400 - {'error': {'message': "You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp'].", 'type': 'invalid_request_error', 'param': None, 'code': 'sanitizer_server_error'}}
ERROR:root:LLM(Large Languate Model) error, Please check your key or base_url, or network

**Comment by CosmosShadow** [comment]
Can you provide the PDF file?
